
export const drawerWidth = 240;

export const formTypes = {

    newVehicle: 'NEW_VEHICLE',
    newUser: 'NEW_USER',
    newPenalty: 'NEW_PENALTY',
    login: 'LOGIN',
    signUp: 'SIGN_UP',
    forgotPassword: 'FORGOT_PASSWORD',
    newPassword: 'NEW_PASSWORD',
    newAutoGeneratedForm: 'NEW_AUTO_GENERATED_FORM',
    autoGenerateForm: 'AUTO_GENERATE_FORM',
}

export const pageType = {
    vehicle: {
        type: 'VEHICLE',
        sortByOptions: [
            "Plate Number",
            "creation date"
        ],
    },
    penalty: {
        type: 'PENALTY',
        sortByOptions: [
            "Plate Number", "receipt no", "owner name", "penalty date"
        ],
    },
    users: {
        type: 'USERS',
        sortByOptions: [
            "Name",
            "creation date"
        ],
    },
}


export const excelFileType = {
    //attached to excel to identify page type. for menu data, the added menu will be used as file type 
    vehicle: "VEHICLE",
    penalty: "PENALTY",
}
export const paymentStatus = ['Pending','Settled',]

export const signUpTextfields  = [
    {
        placeholder: "Name",
        name: "name",
        type: "text"

    },
    {
        placeholder: "Surname",
        name: "surname",
        type: "text"

    },
    {
        placeholder: "Email",
        name: "email",
        type: "email"

    },
    {
        placeholder: "password",
        name: "password",
        type: "password"

    },
]


export const vehicleTextFields = [
    {
        placeholder: "Plaka No",
        name: "plate_number"

    },
    {
        placeholder: "Araç Grubu",
        name: "vehicle_group"

    },
    {
        placeholder: "Marka-Model",
        name: "brand_model"

    },
    {
        placeholder: "Şase No",
        name: "chassis_number"
    },
    {
        placeholder: "Motor No",
        name: "motor_number"
    },
    {
        placeholder: "Model Yılı",
        name: "model_year"
    },
    {
        placeholder: "Renk",
        name: "color"
    },
    {
        placeholder: "Dosya No",
        name: "file_number"
    },
    {
        placeholder: "Künye",
        name: "tag"
    },
    {
        placeholder: "Alım Tipi",
        name: "reception_type"
    },
    {
        placeholder: "Demirbaş No",
        name: "asset_number"
    }
]
export const penaltyTextFields = [
    {
        placeholder: "MAKBUZ-NO",
        name: "receipt_number",
        type: "text"

    },
    {
        placeholder: "CEZA MADDE",
        name: "penalty_article",
        type: "text"

    },
    {
        placeholder: "CEZATUTAR ",
        name: "penalty",
        type: "text"

    },
    {
        placeholder: "NOT ",
        name: "note",
        type: "text"

    },
    {
        placeholder: "ÖDEME YAPAN",
        name: "paying",
        type: "text"

    },
    {
        placeholder: "KAYNAK ",
        name: "source",
        type: "text"

    },
    {
        placeholder: "BİRİM  ",
        name: "unit",
        type: "text"

    },
    {
        placeholder: "İADE ID  ",
        name: "return_id",
        type: "text"

    },
    {
        placeholder: "PESİNTUTAR ",
        name: "pesintutar",
        type: "text"

    },
    {
        placeholder: "İDAYSİSID",
        name: "daysisid",
        type: "text"

    },
    {
        placeholder: "DAYSİSONAY",
        name: "daysisonay",
        type: "text"

    },
]


export const otherFields = [
    {
        name: 'delivery_date',
        placeholder: 'teslim tarihi'
    },
    {
        name: 'updated_at',
        placeholder: 'güncellendi'
    },
    {
        name: 'created_at',
        placeholder: 'oluşturulduğunda'
    },
    {
        name: 'notification_date',
        placeholder: 'TEBLİG TARİHİ'
    },
    {
        name: 'status',
        placeholder: 'ÖDEME DURUMU'
    },
    {
        name: 'payment_date',
        placeholder: 'ÖDEME TARİHİ'
    },
    {
        name: 'penalty_date',
        placeholder: 'CEZA TARİHİ'
    },
    {
        name: 'penalty_hour',
        placeholder: 'CEZA-SAAT'
    },
]